# hint for the IDE which belongs together
kataglyphis_add_source_group("vulkan_base" VULKAN_BASE_FILTER)
kataglyphis_add_source_group("gui" GUI_FILTER)
kataglyphis_add_source_group("gui/imgui" IMGUI_FILTER)
kataglyphis_add_source_group("renderer" RENDERER_FILTER)
kataglyphis_add_source_group("renderer/pc" PC_FILTER)
kataglyphis_add_source_group("renderer/AS" AS_FILTER)
kataglyphis_add_source_group("scene" SCENE_FILTER)
kataglyphis_add_source_group("window" WINDOW_FILTER)
kataglyphis_add_source_group("memory" MEMORY_FILTER)
kataglyphis_add_source_group("common" COMMON_FILTER)
kataglyphis_add_source_group("app" APP_FILTER)
kataglyphis_add_source_group("util" UTIL_FILTER)
