# setting all project filters
# ---- PROJECT FILTER  --- BEGIN
kataglyphis_append_prefixed_files(
  GUI_FILTER
  "${PROJECT_SRC_DIR}gui/"
  GUI.cpp
  GUI.ixx)

kataglyphis_append_prefixed_files(
  RENDERER_FILTER
  "${PROJECT_SRC_DIR}renderer/"
  VulkanRenderer.cpp
  VulkanRenderer.ixx
  PathTracing.cpp
  PathTracing.ixx
  Raytracing.cpp
  Raytracing.ixx
  Rasterizer.cpp
  Rasterizer.ixx
  PostStage.cpp
  PostStage.ixx
  CommandBufferManager.cpp)
kataglyphis_append_prefixed_files(
  RENDERER_FILTER
  "${PROJECT_INCLUDE_DIR}renderer/"
  GlobalUBO.hpp)
kataglyphis_append_prefixed_files(
  RENDERER_FILTER
  "${PROJECT_SRC_DIR}renderer/"
  GUIRendererSharedVars.ixx)
kataglyphis_append_prefixed_files(
  RENDERER_FILTER
  "${PROJECT_INCLUDE_DIR}renderer/"
  SceneUBO.hpp)

kataglyphis_append_prefixed_files(
  PC_FILTER
  "${PROJECT_INCLUDE_DIR}renderer/pushConstants/"
  PushConstantPathTracing.ixx
  PushConstantPost.ixx
  PushConstantRasterizer.ixx
  PushConstantRayTracing.ixx)

kataglyphis_append_prefixed_files(
  AS_FILTER
  "${PROJECT_SRC_DIR}renderer/accelerationStructures/"
  ASManager.ixx)
kataglyphis_append_prefixed_files(
  AS_FILTER
  "${PROJECT_INCLUDE_DIR}renderer/accelerationStructures/"
  BottomLevelAccelerationStructure.hpp
  TopLevelAccelerationStructure.hpp)
kataglyphis_append_prefixed_files(
  AS_FILTER
  "${PROJECT_SRC_DIR}renderer/accelerationStructures/"
  ASManager.cpp)

kataglyphis_append_prefixed_files(
  VULKAN_BASE_FILTER
  "${PROJECT_SRC_DIR}vulkan_base/"
  ShaderHelper.cpp
  VulkanBuffer.cpp
  VulkanBufferManager.cpp
  VulkanDebug.cpp
  VulkanDevice.cpp
  VulkanImage.cpp
  VulkanImageView.cpp
  VulkanInstance.cpp
  VulkanSwapChain.cpp)
kataglyphis_append_prefixed_files(
  VULKAN_BASE_FILTER
  "${PROJECT_INCLUDE_DIR}vulkan_base/"
  ShaderIncludes.hpp)
kataglyphis_append_prefixed_files(
  VULKAN_BASE_FILTER
  "${PROJECT_SRC_DIR}vulkan_base/"
  ShaderHelper.ixx
  VulkanDebug.ixx)

kataglyphis_append_prefixed_files(
  SCENE_FILTER
  "${PROJECT_SRC_DIR}scene/"
  ObjLoader.cpp
  Model.cpp
  Mesh.cpp
  Scene.cpp
  Camera.cpp
  SceneConfig.cpp
  Texture.cpp
  Vertex.cpp
  Camera.ixx)
kataglyphis_append_prefixed_files(
  SCENE_FILTER
  "${PROJECT_INCLUDE_DIR}scene/"
  ObjMaterial.hpp
  Model.hpp
  ObjLoader.hpp
  Mesh.hpp)
kataglyphis_append_prefixed_files(
  SCENE_FILTER
  "${PROJECT_SRC_DIR}scene/"
  Vertex.ixx)
kataglyphis_append_prefixed_files(
  SCENE_FILTER
  "${PROJECT_INCLUDE_DIR}scene/"
  Scene.hpp)
kataglyphis_append_prefixed_files(
  SCENE_FILTER
  "${PROJECT_SRC_DIR}scene/"
  SceneConfig.ixx
  GUISceneSharedVars.ixx
  ObjectDescription.ixx)
kataglyphis_append_prefixed_files(
  SCENE_FILTER
  "${PROJECT_INCLUDE_DIR}scene/"
  Texture.hpp)

kataglyphis_append_prefixed_files(
  WINDOW_FILTER
  "${PROJECT_SRC_DIR}window/"
  Window.cpp
  Window.ixx)

kataglyphis_append_prefixed_files(
  UTIL_FILTER
  "${PROJECT_SRC_DIR}util/"
  File.ixx
  File.module.cpp)

kataglyphis_append_prefixed_files(
  APP_FILTER
  "${PROJECT_SRC_DIR}app/"
  App.cpp
  App.ixx)

kataglyphis_append_prefixed_files(
  COMMON_FILTER
  "${PROJECT_INCLUDE_DIR}common/"
  FormatHelper.hpp
  Globals.hpp
  MemoryHelper.hpp
  Utilities.hpp)

kataglyphis_append_prefixed_files(
  MEMORY_FILTER
  "${PROJECT_SRC_DIR}memory/"
  Allocator.ixx
  Allocator.cpp)

kataglyphis_append_prefixed_files(MAIN_FILTER "${PROJECT_SRC_DIR}" Main.cpp)
