#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16f) uniform writeonly image2D outputImage;
layout(set = 0, binding = 1) uniform sampler3D noiseTexture;

#include "../common/SceneUBO.glsl"

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);

    if(texelCoord.x >= size.x || texelCoord.y >= size.y) {
        return;
    }

    vec4 color = vec4(1.0, 1.0, 1.0, 0.5); // Placeholder cloud color

    imageStore(outputImage, texelCoord, color);
}
