name: Linux build + test + coverage on Ubuntu 24.04 ARM

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-arm:
    uses: ./.github/workflows/Linux.yml
    with:
      runner: ubuntu-24.04-arm
    secrets:
      SERVER: ${{ secrets.SERVER }}
      USERNAME: ${{ secrets.USERNAME }}
      PW: ${{ secrets.PW }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
