name: Linux build reusable

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    secrets:
      SERVER:
        required: true
      USERNAME:
        required: true
      PW:
        required: true
      CODECOV_TOKEN:
        required: true
      GHCR_PAT:
        required: true

env:
  BUILD_TYPE: Debug
  GCC_PROFILE_PRESET: linux-profile-GNU
  CLANG_PROFILE_PRESET: linux-profile-clang
  VULKAN_VERSION: 1.4.328.1
  # folder/name configuration -- change here to affect the whole workflow
  BUILD_DIR: build
  BUILD_RELEASE_DIR: build-release
  DOCS_OUT: build/build/html
  COVERAGE_JSON: build/coverage.json

  CONTAINER_IMAGE: ghcr.io/kataglyphis/kataglyphis_beschleuniger:latest

jobs:
  build_and_test:
    runs-on: ${{ inputs.runner }}
    # Run this job inside the GHCR container:

    steps:
      - name: Free Disk Space on Host
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull container image
        run: |
          for i in 1 2 3; do
            echo "Attempt $i to pull container (${{ inputs.runner }})..."
            if timeout 900 docker pull "${{ env.CONTAINER_IMAGE }}"; then
              echo "Successfully pulled container"
              exit 0
            fi
            echo "Pull failed, waiting before retry..."
            sleep 30
          done
          echo "Failed to pull container after 3 attempts"
          exit 1

      #################################################################################################################
      ####################### Run unit/integration/fuzzy/coverage/tests/static analyzers ##############################
      #################################################################################################################
      - name: Set compiler to clang
        run: |
          echo "COMPILER=clang" >> "$GITHUB_ENV"
          echo "PRESET=linux-debug-clang" >> "$GITHUB_ENV"
          echo "PROFILE_PRESET=${CLANG_PROFILE_PRESET}" >> "$GITHUB_ENV"
          echo "BUILD_DIR=build-clang" >> "$GITHUB_ENV"
          echo "COVERAGE_JSON=build-clang/coverage.json" >> "$GITHUB_ENV"

      #################################################################################################################
      ############################################### clang: build/test ################################################
      #################################################################################################################

      - name: Prepare for unit/integration tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e VULKAN_VERSION=${{ env.VULKAN_VERSION }} \
            -e BUILD_DIR=${{ env.BUILD_DIR }} \
            -e MATRIX_COMPILER=${{ matrix.compiler }} \
            "${{ env.CONTAINER_IMAGE }}" \
            bash -lc '
            set -e
            git config --global --add safe.directory /workspace || true

            if [ "$MATRIX_COMPILER" = "clang" ]; then
              PRESET="linux-debug-clang"
            else
              PRESET="linux-debug-GNU"
            fi

            . "/opt/vulkan/${VULKAN_VERSION}/setup-env.sh"
            cmake -B "${BUILD_DIR}" --preset "${PRESET}"
            cmake --build "${BUILD_DIR}" --preset "${PRESET}"
            '

      - name: Run Unit/Integration tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/${{ env.BUILD_DIR }} \
            -e BUILD_TYPE=${{ env.BUILD_TYPE }} \
            "${{ env.CONTAINER_IMAGE }}" \
            bash -lc '
            set -e
            ctest -C "${BUILD_TYPE}" --verbose --extra-verbose --debug -T test --output-on-failure -E Integration.VulkanEngine RendererTest.BasicSetup
            '

      - name: Run fuzzer tests
        run: |
          ${{ env.BUILD_DIR }}/first_fuzz_test
        working-directory: ${{ github.workspace }}

      - name: Build Code Coverage
        run: |
          llvm-profdata merge -sparse ${{ env.BUILD_DIR }}/Test/compile/default.profraw -o ${{ env.BUILD_DIR }}/compileTestSuite.profdata
          llvm-cov report ${{ env.BUILD_DIR }}/compileTestSuite -instr-profile=${{ env.BUILD_DIR }}/compileTestSuite.profdata
          llvm-cov export ${{ env.BUILD_DIR }}/compileTestSuite -format=text -instr-profile=${{ env.BUILD_DIR }}/compileTestSuite.profdata > ${{ env.COVERAGE_JSON }}
          llvm-cov show ${{ env.BUILD_DIR }}/compileTestSuite -instr-profile=${{ env.BUILD_DIR }}/compileTestSuite.profdata
        working-directory: ${{ github.workspace }}

      - name: Codecov
        if: ${{ inputs.runner == 'ubuntu-24.04' }}
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.COVERAGE_JSON }}
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false

      # runs for ever so disable
      #- name: Run clang tidy
      #  continue-on-error: true
      #  run: clang-tidy -p=./${{ env.BUILD_DIR }}/compile_commands.json  $(find Src -name '*.cpp' -o -name '*.cc')

      - name: Run Clang static analysis (HTML)
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            "${{ env.CONTAINER_IMAGE }}" \
            bash -lc '
            set -e
            clang++ --analyze -DUSE_RUST=1 -Xanalyzer -analyzer-output=html $(find Src -name "*.cpp" -o -name "*.cc")
            '

      - name: Run Clang static analysis (scan-build)
        continue-on-error: true
        run: |
          mkdir -p scan-build-reports
          scan-build-21 -o scan-build-reports cmake --build "${BUILD_DIR}" --preset "${PRESET}"
        working-directory: ${{ github.workspace }}

      #################################################################################################################
      ############################# Now run on performance benchmarking/profiling #####################################
      #################################################################################################################
      - name: Configure/build CMake for Profiling (select preset by compiler)
        run: |
          rm -r "${{ env.BUILD_DIR }}"
          PRESET="${PROFILE_PRESET}"
          echo "Using preset: ${PRESET}"
          # ${{ github.workspace }}
          . "/opt/vulkan/${{ env.VULKAN_VERSION }}/setup-env.sh"
          cmake -B "${{ env.BUILD_DIR }}" --preset "${PRESET}"
          cmake --build "${{ env.BUILD_DIR }}" --preset "${PRESET}"
        working-directory: ${{ github.workspace }}

      - name: Run performance benchmarks
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e BUILD_DIR=${{ env.BUILD_DIR }} \
            "${{ env.CONTAINER_IMAGE }}" \
            bash -lc '
            set -e
            "${BUILD_DIR}/perfTestSuite"
            '
        
      #################################################################################################################
      ######################################## Build docs #############################################################
      #################################################################################################################
      - name: Set Astral UV venv
        if: ${{ inputs.runner == 'ubuntu-24.04' }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            "${{ env.CONTAINER_IMAGE }}" \
            bash -lc '
            set -e
            uv venv
            '

      - name: Setup python env
        if: ${{ inputs.runner == 'ubuntu-24.04' }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            "${{ env.CONTAINER_IMAGE }}" \
            bash -lc '
            set -e
            . ".venv/bin/activate"
            uv pip install -r requirements.txt
            '

      - name: Build web page
        if: ${{ inputs.runner == 'ubuntu-24.04' }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e DOCS_OUT=${{ env.DOCS_OUT }} \
            "${{ env.CONTAINER_IMAGE }}" \
            bash -lc '
            set -e
            cp ${DOCS_OUT}/*.svg ./docs/source/_static
            cd docs/source
            uv run python graphviz_generator.py
            cd ..
            uv run make html
            '

      - name: 📂 Sync files to domain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        if: ${{ inputs.runner == 'ubuntu-24.04' }}
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PW }}
          local-dir: "./docs/build/html/"

      #################################################################################################################
      ############################################### gcc: build/test #################################################
      #################################################################################################################

      - name: Set compiler to gcc
        run: |
          echo "COMPILER=gcc" >> "$GITHUB_ENV"
          echo "PRESET=linux-debug-GNU" >> "$GITHUB_ENV"
          echo "PROFILE_PRESET=${GCC_PROFILE_PRESET}" >> "$GITHUB_ENV"
          echo "BUILD_DIR=build-gcc" >> "$GITHUB_ENV"

      - name: Prepare for unit/integration tests (gcc)
        run: |
          . "/opt/vulkan/${{ env.VULKAN_VERSION }}/setup-env.sh"
          cmake -B ${{ env.BUILD_DIR }} --preset "$PRESET"
          cmake --build ${{ env.BUILD_DIR }} --preset "$PRESET"
        working-directory: ${{ github.workspace }}

      - name: Run Unit/Integration tests (gcc)
        working-directory: ${{ env.BUILD_DIR }}
        run: ctest -C ${{env.BUILD_TYPE}} --verbose --extra-verbose --debug -T test --output-on-failure -E Integration.VulkanEngine RendererTest.BasicSetup

      - name: Run fuzzer tests (gcc)
        run: |
          echo "Compiled with GCC so no fuzz testing!"
        working-directory: ${{ github.workspace }}

      - name: Build Code Coverage (gcc)
        run: |
          gcovr -r .
        working-directory: ${{ github.workspace }}

      - name: Configure/build CMake for Profiling (gcc)
        run: |
          rm -r "${{ env.BUILD_DIR }}"
          PRESET="${PROFILE_PRESET}"
          echo "Using preset: ${PRESET}"
          . "/opt/vulkan/${{ env.VULKAN_VERSION }}/setup-env.sh"
          cmake -B "${{ env.BUILD_DIR }}" --preset "${PRESET}"
          cmake --build "${{ env.BUILD_DIR }}" --preset "${PRESET}"
        working-directory: ${{ github.workspace }}

      - name: Run performance benchmarks (gcc)
        run: ${{ env.BUILD_DIR }}/perfTestSuite
        working-directory: ${{ github.workspace }}

      #################################################################################################################
      ######################################## Release: build + package ################################################
      #################################################################################################################

      - name: Configure/build CMake for Release
        run: |
          . "/opt/vulkan/${{ env.VULKAN_VERSION }}/setup-env.sh"
          cmake -B "${{ env.BUILD_RELEASE_DIR }}" --preset linux-release-clang
          cmake --build "${{ env.BUILD_RELEASE_DIR }}" --config Release
        working-directory: ${{ github.workspace }}

      - name: Package
        run: |
          . "/opt/vulkan/${{ env.VULKAN_VERSION }}/setup-env.sh"
          cmake --build "${{ env.BUILD_RELEASE_DIR }}" --target package
        working-directory: ${{ github.workspace }}

      - name: Upload Linux Packages (Clang only)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-packages
          path: |
            ${{ env.BUILD_RELEASE_DIR }}/*.tar.gz
            ${{ env.BUILD_RELEASE_DIR }}/*.tgz
            ${{ env.BUILD_RELEASE_DIR }}/*.deb
