name: Linux build + test + coverage on Ubuntu 24.04 x86

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-x64:
    uses: ./.github/workflows/Linux.yml
    with:
      runner: ubuntu-24.04
    secrets:
      SERVER: ${{ secrets.SERVER }}
      USERNAME: ${{ secrets.USERNAME }}
      PW: ${{ secrets.PW }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
