name: PowerShell modules tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'MyLibrary/**'

jobs:
  test-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Run Pester tests (Windows PowerShell)
        shell: pwsh
        run: |
          $env:PSModulePath = "$PWD/MyLibrary/modules;$env:PSModulePath"
          Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.0.0 -AllowClobber
          pwsh -Command "Invoke-Pester -Script '.\MyLibrary\tests' -Output Detailed"

  test-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
      - name: Run Pester tests (pwsh)
        shell: bash
        run: |
          pwsh -c "$env:PSModulePath='$PWD/MyLibrary/modules;$env:PSModulePath'; Install-Module -Name Pester -Force -Scope CurrentUser -MinimumVersion 5.0.0 -AllowClobber"
          pwsh -c "Invoke-Pester -Script './MyLibrary/tests' -Output Detailed"
